import json

CODE_RELATION = {
    "AG PRIME COMERCIO DE PNEUS PEÇAS & SERV.AUTOMOTIVO": 5000905,
    "ANA LUCIA MARCONE DE SOUSA": 5001446,
    "CARAJAS MAT DE CONST. LTDA - JP": 5000511,
    "KARNE KEIJO LOG. INTEGRADA LTDA": 5001451,
    "MAGAZINE LUIZA S/A": 5002139,
    "MAIS CLEAN HIGIENIZACAO LTDA - ME": 5001447,
    "MEX COMERCIO DE PRODUTO DE HIGIENE, SANITIZACAO E": 5003310,
    "PROJECTA - MATERIAL DE CONSTRUÇAO LTDA.": 5000595,
    "TRES CORACOES ALIMENTOS S.A": 5001081,
    "BOOKING.COM BRASIL SERVICOS DE RESERVA DE HOTEIS": 25131,
    "FRIGELAR COMERCIO E INDUSTRIAL LTDA": 25134,
    "TEKA TECELAGEM KUEHNRICH S A": 25149,
    "DESINSETIZADORA RATINSET LTDA-ME": 25154,
    "QUICKLY TRAVEL AGENCIA DE VIAGENS E TURISMO LTDA": 4882,
    "DIEGO LIMA VIANA SILVEIRA": 4885,
    "AÇÃO CONTABIL": 4898,
    "KALUNGA COM. E IND. GRÁFICA LTDA": 4919,
    "INDAIA BRASIL AGUAS MINERAIS LTDA": 4928,
    "AMX COLCHOES MG LTDA": 4938,
    "EXJET COMERCIO DE SERVIÇOS CONTRA INCENDIO LTDA": 4961,
    "LATICINIO BELO VALE LTDA": 4947,
    "FERRIRA COSTA & CIA LTDA": 4950,
    "N CLAUDINO E CIA LTDA - MANAIRA": 5626,
    "CAPITAL COMERCIO DE MATERIAL DE CONSTRUCAO EIRELI": 5630,
    "SUPER COMERCIO DE PRODUTOS SANEANTES DOMISSANITARI": 5639,
    "INDUSTRIA E COMERCIO DE LATICINIOS IDEAL LTDA- EPP": 5641,
    "CONSTA SERVIÇO DE ANÁLISE DE ÁGUA LTDA": 5658,
    "EVANNE DA CUNHA DIAS": 5672,
    "MAGAZINE TORRA TORRA LTDA": 5676,
    "UNIVERSO DOS FILTROS COMERCIO E SERVIÇOS DE ELETRO": 5678,
    "LINX SISTEMAS E CONSULTORA LTDA": 5681,
    "NEURIZETE PEREIRA DE SOUSA": 5687,
    "LIMPPLAST COMERCIO DE DESCARTAVEIS EIRELI": 5688,
    "PROJECTA MATERIAL DE CONSTRUÇÃO": 5694,
    "AMBIENTAL FILTROS LTDA": 5737,
    "LEF PANIFICADORA E COMERCIO DE ALIMENTOS LTDA": 5697,
    "MERCADO AQUECIMENTO LTDA": 5738,
    "EMMA SEGURANÇA EM MEDICINA DO TRABALHO": 5703,
    "SRS MONTEIRO LTDS": 5717,
    "FORTE FRUTOS COMERCIAL LTDA": 5719,
    "São Bras S/A Ind Com de Alimentos": 5721,
    "SET SISTEMAS E PRODUTOS TECNICOS LTDA": 5722,
    "PALACIO DAS FERRAMENTAS E PARAFUSOS": 5742,
    "AMAZON TEMPER PARAIBA IND E COM DE VIDROS": 5776,
    "JUROS": 4701,
}


class CodesProvider:
    relation: dict[str, int]

    def __init__(self):
        self.relation = self.__upper_dict(CODE_RELATION)

    def credit(self, entity: str) -> str:
        value = self.relation.get(entity.upper())
        print(self.relation)
        return str(value) if value else ""

    def debit(self, _: str) -> str:
        value = self.relation.get("JUROS") or 4701
        return str(value) if value else ""

    def set_codes_relation_from_json(self, path: str):
        with open(path, "r") as file:
            data = json.load(file)
            self.relation = self.__upper_dict(data)

    def __upper_dict(self, d: dict):
        return {k.upper(): v for k, v in d.items()}
